### PR TITLE
Fix repository url parser in LicenseSuggestion

### LINKED ISSUE #1278: Bug: License suggestion fails to parse URLs of repositories with ".git" in its name
License suggestion mistakenly truncates repository name when it contains ".git" (which is common in repositories for .github.io websites).

For example, if an user inputs repository urls like "https://github.com/octocat/octocat.github.io", license suggestion will falsely split url at the middle of repo name, drop ".github.io" and return the result of "octocat/octocat".

Image

### PR DESCRIPTION
**Pull request by Cycloctane**
Update regex. Replace `String.split` with `String.replace` to trim ".git" suffix.

Fixes #1278

### CODE REVIEW

File: assets/js/app.coffee [hunk 1]
```diff
@@ -112,14 +112,9 @@ class LicenseSuggestion
 
   # Try to extract the repository full name from the user input
   parseUserInput: (userInput) ->
-    repository = /https?:\/\/github\.com\/(.*?)\/(.+)(\.git)?$/.exec userInput
+    repository = /https?:\/\/github\.com\/([^\/]+)\/([^\/]+)\/?$/.exec userInput
```
Comment (mlinksva) [inline assets/js/app.coffee]: Nice simplification but I don't see any reason to reject a URL with trailing garbage, say someone copies a repo URL that includes a filename or `?tab=...` which are pretty easy to get if not paying close attention. Wonder if simply matching up to the end of the second path item and ignoring anything after that wouldn't work.
```suggestion
    repository = /https?:\/\/github\.com\/([^\/]+)\/([^\/]+)/.exec userInput
```

**Review by mlinksva — CHANGES_REQUESTED** [review]

File: assets/js/app.coffee (hunk 1 above)
Comment (Cycloctane) [reply assets/js/app.coffee]: I think it makes sense. I also added `?` and `#` to negated class in the second group to ignore query and fragment.

**Review by mlinksva — APPROVED** [review]

**Review by THAIuLINH01 — COMMENTED** [review]
[](url)
